name: Express App Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Install nodejs
        run: sudo apk add --update nodejs npm

      - name: Install depenendencies
        run: cd ~/code/ && npm install

      - name: Install pm2
        run: sudo npm install pm2@latest -g

  deploy:
    steps:
      - name: Start App with pm2
        run: pm2 delete "express-app" || true && pm2 start main.js --name "express-app"

      - name: Save pm2 config
        run: pm2 save
